name: 'Scripting Action'
author: 'Janina Wibker'
description: |
  Proper scripting with TypeScript in Github Actions using bun. Includes sane defaults, useful helpers, an authenticated octokit instance and other useful integrations.
  Inspired by actions/github-script.

branding:
  icon: 'package'
  color: 'purple'

inputs:
  file:
    description: 'Relative path to typescript file. This requires doing a checkout beforehand. Can only specify either `file` or `script`, not both. Assumes the default export is the async function to run. See docs for details about the function signature, how to pass in arguments, how module resolution works and more.'
    required: false

  script:
    description: 'Inline typescript, same behavior as `file`, but acting as the body of a function instead of an entire file with a default export. Can only specify either `file` or `script`, not both. See docs for more details.'
    required: false

  input_encoding:
    description: 'Either string or json, see `input`.'
    required: false
    default: 'string'

  input:
    description: 'Input passed to script. Depending on `input-encoding` either assumed to be a string, or passed to `JSON.parse`. Defaults to `""` or `{}` respectively. Alternatively to easier pass in more values at once use environment variables.'
    required: false

  result_encoding:
    description: 'Either string or json, see `result`.'
    required: false
    default: 'string'

  token:
    description: 'The GitHub token used to create an authenticated client'
    default: '${{ github.token }}'
    required: true

  debug:
    description: 'Whether to tell the GitHub client to log details of its requests. true or false. Default is to run in debug mode when the GitHub Actions step debug logging is turned on.'
    default: "${{ runner.debug == '1' }}"

outputs:
  result:
    description: 'The return value of the script. Depending on `result-encoding` either assumed to be a string, or passed to `JSON.stringify`'
    value: '${{ steps.run.outputs.result }}'

runs:
  using: 'composite'
  steps:
    - name: 'Install bun'
      uses: 'oven-sh/setup-bun@v2.1.2'
      with:
        bun-version-file: '${{ github.action_path }}/package.json'

    - name: 'Install dependencies'
      working-directory: '${{ github.action_path }}'
      shell: 'sh'
      env:
        GITHUB_TOKEN: '${{ inputs.token }}'
      run: 'bun install'

    - name: 'Run script'
      id: 'run'
      shell: 'sh'
      env:
        # TODO: further evidence that github actions is absolutely shit and no one should be using it.
        # TODO: https://github.com/actions/github-script/issues/56
        # TODO: this has been open for over 5 years and is still unfixed, this just shows how broken
        # TODO: everything that microsoft touches is.
        INPUT_FILE: '${{ inputs.file }}'
        INPUT_SCRIPT: '${{ inputs.script }}'
        INPUT_INPUT_ENCODING: '${{ inputs.input_encoding }}'
        INPUT_INPUT: '${{ inputs.input }}'
        INPUT_RESULT_ENCODING: '${{ inputs.result_encoding }}'
        INPUT_TOKEN: '${{ inputs.token }}'
        INPUT_DEBUG: '${{ inputs.debug }}'
        INPUT_RESULT: '${{ inputs.result }}'

        ACTION_PATH: '${{ github.action_path }}'
        ACTION_WORKSPACE: '${{ github.workspace }}'
      run: |
        PATH_A="${{ github.action_path }}/node_modules"
        PATH_B="${{ github.workspace }}/node_modules"
        PATH_C="${{ github.workspace }}/.github/node_modules"
        PATH_D="${{ github.workspace }}/.github/workflows/node_modules"

        export NODE_PATH="$NODE_PATH:$PATH_A:$PATH_B:$PATH_C:$PATH_D"

        bun run \
          --bun \
          --cwd="${{ github.workspace }}" \
          "${{ github.action_path }}/src/index.ts"
